[tool.poetry]
name = "graia-saya"
version = "0.0.1"
description = ""
authors = ["GreyElaina <31543961+GreyElaina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
graia-broadcast = "^0.5.3"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
